version: '3.1'

services:
  db:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "docker" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_DB: skate
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: chusaiyu3Xah8eefees3ealohgh0uJeiw9oeh1oh
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  api:
    build: .
    command: uvicorn skatebase.asgi:app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
