"""Add User Table

Revision ID: 42b143f7cdb4
Revises:
Create Date: 2021-07-29 16:50:50.945326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42b143f7cdb4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("fullname", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
